modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/JackyyTV/${jar_name}/issues"

[[mods]]
modId="${mod_id}"
version="${mc_version}-${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/JackyyTV/${jar_name}"
logoFile="logo.png"
credits="ThatGamerBlue, ColossalPercy, JCOnline and many other people that helped the development of this mod!"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="gunpowderlib"
    mandatory=true
    versionRange="[1.18.2-2.0.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cofh_core"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="thermal"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="thermal_innovation"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="mekanism"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
